---
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/svenlito/terraform-aws-eventbridge
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
